apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: calculator-clusterip
  name: calculator-clusterip
spec:
  ports:
  - name: 9000-9000
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: calculator-deploy
  type: ClusterIP
status:
  loadBalancer: {}
