apiVersion: v1  
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort  # Day 12
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # ClusterIP service port
      targetPort: 80   # The container’s port
      nodePort: 31000  # NodePort (must be within 30000-32767)
