apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: deployment
  name: deployment
spec:
  containers:
  - args:
    - flask-app
    image: litu2rout/flask-ci-test:v1
    name: deployment
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
