apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"labels":{"app":"flask-app"},"name":"newpd","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"tier":"newpd"}},"template":{"metadata":{"labels":{"tier":"newpd"}},"spec":{"containers":[{"image":"litu2rout/flask-ci-test:v1","name":"flask-conatiner","ports":[{"containerPort":5000}]}]}}}}
    creationTimestamp: "2025-07-06T10:55:49Z"
    generation: 1
    labels:
      app: flask-app
    name: newpd
    namespace: default
    resourceVersion: "35626"
    uid: 8f45c49d-6652-4833-aaf4-80b8e52f30db
  spec:
    replicas: 3
    selector:
      matchLabels:
        tier: newpd
    template:
      metadata:
        creationTimestamp: null
        labels:
          tier: newpd
      spec:
        containers:
        - image: litu2rout/flask-ci-test:v1
          imagePullPolicy: IfNotPresent
          name: flask-conatiner
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    fullyLabeledReplicas: 3
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
