apiVersion: v1
kind: Pod
metadata: 
 name: newpd
 labels:
   app: flask-app
spec:
  containers:
    - name: flask-conatiner
      image: litu2rout/flask-ci-test:v1
      ports:
      - containerPort: 5000
        
   
