apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
 - name: newpd1 
   labels: 
   env: dev
spec: 
  replica: 3
  selector:
   matchlabels:
     env: dev
  template:
    metadata:
     labels:
       env: dev
  spec:
   conatiners:
   - name: nginx-pod
     image: nginx:1.23.4
      ports:
       - containerPort: 80



